;;-*-coding: emacs-mule;-*-
(define-abbrev-table 'apropos-mode-abbrev-table '(
    ))

(define-abbrev-table 'awk-mode-abbrev-table '(
    ))

(define-abbrev-table 'bsh-script-mode-abbrev-table '(
    ))

(define-abbrev-table 'c++-mode-abbrev-table '(
    ))

(define-abbrev-table 'c-mode-abbrev-table '(
    ))

(define-abbrev-table 'comint-mode-abbrev-table '(
    ))

(define-abbrev-table 'csv-mode-abbrev-table '(
    ))

(define-abbrev-table 'erc-mode-abbrev-table '(
    ))

(define-abbrev-table 'fundamental-mode-abbrev-table '(
    ))

(define-abbrev-table 'global-abbrev-table '(
    ))

(define-abbrev-table 'html-mode-abbrev-table '(
    ))

(define-abbrev-table 'idl-mode-abbrev-table '(
    ))

(define-abbrev-table 'java-mode-abbrev-table '(
    ))

(define-abbrev-table 'jde-mode-abbrev-table '(
    ("catch" "catch" c-electric-continued-statement 0)
    ("else" "else" c-electric-continued-statement 0)
    ("finally" "finally" c-electric-continued-statement 0)
    ("while" "while" c-electric-continued-statement 0)
    ))

(define-abbrev-table 'jde-run-mode-abbrev-table '(
    ))

(define-abbrev-table 'lisp-mode-abbrev-table '(
    ))

(define-abbrev-table 'newsticker-mode-abbrev-table '(
    ))

(define-abbrev-table 'objc-mode-abbrev-table '(
    ))

(define-abbrev-table 'pike-mode-abbrev-table '(
    ))

(define-abbrev-table 'python-mode-abbrev-table '(
    ))

(define-abbrev-table 'select-tags-table-mode-abbrev-table '(
    ))

(define-abbrev-table 'sgml-mode-abbrev-table '(
    ))

(define-abbrev-table 'shell-mode-abbrev-table '(
    ))

(define-abbrev-table 'sldb-mode-abbrev-table '(
    ))

(define-abbrev-table 'slime-compiler-notes-mode-abbrev-table '(
    ))

(define-abbrev-table 'slime-connection-list-mode-abbrev-table '(
    ))

(define-abbrev-table 'slime-fuzzy-completions-mode-abbrev-table '(
    ))

(define-abbrev-table 'slime-inspector-mode-abbrev-table '(
    ))

(define-abbrev-table 'slime-thread-control-mode-abbrev-table '(
    ))

(define-abbrev-table 'slime-xref-mode-abbrev-table '(
   ))

(define-abbrev-table 'sql-mode-abbrev-table '(
    ("ct" "CREATE TABLE " )
    ("ci" "CREATE INDEX " )
    ("cv" "CREATE VIEW ")
    ("dt" "DROP TABLE ")
    ("di" "DROP INDEX ")
    ("xps" "EXPLAIN SELECT")
    ("xp" "EXPLAIN")
    ("des" "DESCRIBE")
    ("stab" "SHOW TABLES")
    ("sl" "SELECT" nil 1)
    ("sld" "SELECT DISTINCT" nil 1)
    ("slc" "SELECT COUNT(*) as cou" nil 1)
    ("cnt" "COUNT(*) AS cou")
    ("isto"     "INSERT INTO")  ;; I can no longer type in mephisto
    ("fr" "FROM")
    ("wh" "WHERE")
    ("gb" "GROUP BY")
    ("ob" "ORDER BY")
    ("fr" "FROM")
    ("as" "AS")
    ("in" "IN")
    ("and" "AND")
    ("not" "NOT")
    ("ex"  "EXISTS")
    ("exists" "EXISTS")
    ("asc" "ASC")
    ("desc" "DESC")
    ("vc"   "VARCHAR(")
    ("db"   "DOUBLE")
    ("int"  "INT")
    ("intu"  "INT UNSIGNED")
    ("smi"  "SMALLINT")
    ("smiu"  "SMALLINT UNSIGNED")
    ("bgi"  "BIGINT")
    ("bgiu"  "BIGINT UNSIGNED")
    ("data" "data")
    ("Data" "Data")
    ("ntn"  "NOT NULL")
    ("aintn" "AUTO_INCREMENT NOT NULL")
    ("fkr"   "FOREIGN KEY () REFERENCES")

    ("unsigned" "UNSIGNED")
    ("comment"  "COMMENT")
    ("absolute"            "ABSOLUTE")		       
    ("action"	       "ACTION")		       
    ("add"		       "ADD")			       
    ("admin"	       "ADMIN")		       
    ("after"	       "AFTER")		       
    ("aggregate"	       "AGGREGATE")		       
    ("alias"	       "ALIAS")		       
    ("all"		       "ALL")			       
    ("allocate"	       "ALLOCATE")		       
    ("alter"	       "ALTER")		       
    ("and"		       "AND")			       
    ("any"		       "ANY")			       
    ("are"		       "ARE")			       
    ("as"		       "AS")			       
    ("asc"		       "ASC")			       
    ("assertion"	       "ASSERTION")		       
    ("at"		       "AT")			       
    ("authorization"       "AUTHORIZATION")	       
    ("before"	       "BEFORE")		       
    ("begin"	       "BEGIN")		       
    ("both"		       "BOTH")			       
    ("breadth"	       "BREADTH")		       
    ("by"		       "BY")			       
    ("call"		       "CALL")			       
    ("cascade"	       "CASCADE")		       
    ("cascaded"	       "CASCADED")		       
    ("case"		       "CASE")			       
    ("catalog"	       "CATALOG")		       
    ("check"	       "CHECK")		       
    ("class"	       "CLASS")		       
    ("close"	       "CLOSE")		       
    ("collate"	       "COLLATE")		       
    ("collation"	       "COLLATION")		       
    ("column"	       "COLUMN")		       
    ("commit"	       "COMMIT")		       
    ("completion"	       "COMPLETION")		       
    ("connect"	       "CONNECT")		       
    ("connection"	       "CONNECTION")		       
    ("constraint"	       "CONSTRAINT")		       
    ("constraints"	       "CONSTRAINTS")		       
    ("constructor"	       "CONSTRUCTOR")		       
    ("continue"	       "CONTINUE")		       
    ("corresponding"       "CORRESPONDING")	       
    ("create"	       "CREATE")		       
    ("cross"	       "CROSS")		       
    ("cube"		       "CUBE")			       
    ("current"	       "CURRENT")		       
    ("cursor"	       "CURSOR")		       
    ("cycle"	       "CYCLE")		       
    ("day"		       "DAY")			       
    ("deallocate"	       "DEALLOCATE")		       
    ("declare"	       "DECLARE")		       
    ("default"	       "DEFAULT")		       
    ("deferrable"	       "DEFERRABLE")		       
    ("deferred"	       "DEFERRED")		       
    ("delete"	       "DELETE")		       
    ("depth"	       "DEPTH")		       
    ("deref"	       "DEREF")		       
    ("desc"		       "DESC")			       
    ("describe"	       "DESCRIBE")		       
    ("descriptor"	       "DESCRIPTOR")		       
    ("destroy"	       "DESTROY")		       
    ("destructor"	       "DESTRUCTOR")		       
    ("deterministic"       "DETERMINISTIC")	       
    ("diagnostics"	       "DIAGNOSTICS")		       
    ("dictionary"	       "DICTIONARY")		       
    ("disconnect"	       "DISCONNECT")		       
    ("distinct"	       "DISTINCT")		       
    ("domain"	       "DOMAIN")		       
    ("drop"		       "DROP")			       
    ("dynamic"	       "DYNAMIC")		       
    ("each"		       "EACH")			       
    ("else"		       "ELSE")			       
    ("end"		       "END")			       
    ("equals"	       "EQUALS")		       
    ("escape"	       "ESCAPE")		       
    ("every"	       "EVERY")		       
    ("except"	       "EXCEPT")		       
    ("exception"	       "EXCEPTION")		       
    ("exec"		       "EXEC")			       
    ("execute"	       "EXECUTE")		       
    ("external"	       "EXTERNAL")		       
    ("false"	       "FALSE")		       
    ("fetch"	       "FETCH")		       
    ("first"	       "FIRST")		       
    ("for"		       "FOR")			       
    ("foreign"	       "FOREIGN")		       
    ("found"	       "FOUND")		       
    ("free"		       "FREE")			       
    ("from"		       "FROM")			       
    ("full"		       "FULL")			       
    ("function"	       "FUNCTION")		       
    ("general"	       "GENERAL")		       
    ("get"		       "GET")			       
    ("global"	       "GLOBAL")		       
    ("go"		       "GO")			       
    ("goto"		       "GOTO")			       
    ("grant"	       "GRANT")		       
    ("group"	       "GROUP")		       
    ("grouping"	       "GROUPING")		       
    ("having"	       "HAVING")		       
    ("host"		       "HOST")			       
    ("hour"		       "HOUR")			       
    ("identity"	       "IDENTITY")		       
    ("ignore"	       "IGNORE")		       
    ("immediate"	       "IMMEDIATE")		       
    ("in"		       "IN")			       
    ("indicator"	       "INDICATOR")		       
    ("initialize"	       "INITIALIZE")		       
    ("initially"	       "INITIALLY")		       
    ("inner"	       "INNER")		       
    ("inout"	       "INOUT")		       
    ("input"	       "INPUT")		       
    ("insert"	       "INSERT")		       
    ("intersect"	       "INTERSECT")		       
    ("into"		       "INTO")			       
    ("is"		       "IS")			       
    ("isolation"	       "ISOLATION")		       
    ("iterate"	       "ITERATE")		       
    ("join"		       "JOIN")			       
    ("key"		       "KEY")			       
    ("language"	       "LANGUAGE")		       
    ("last"		       "LAST")			       
    ("lateral"	       "LATERAL")		       
    ("leading"	       "LEADING")		       
    ("left"		       "LEFT")			       
    ("less"		       "LESS")			       
    ("level"	       "LEVEL")		       
    ("like"		       "LIKE")			       
    ("limit"	       "LIMIT")		       
    ("local"	       "LOCAL")		       
    ("locator"	       "LOCATOR")		       
    ("map"		       "MAP")			       
    ("match"	       "MATCH")		       
    ("minute"	       "MINUTE")		       
    ("modifies"	       "MODIFIES")		       
    ("modify"	       "MODIFY")		       
    ("module"	       "MODULE")		       
    ("month"	       "MONTH")		       
    ("names"	       "NAMES")		       
    ("natural"	       "NATURAL")		       
    ("new"		       "NEW")			       
    ("next"		       "NEXT")			       
    ("no"		       "NO")			       
    ("none"		       "NONE")			       
    ("not"		       "NOT")			       
    ("null"		       "NULL")			       
    ("of"		       "OF")			       
    ("off"		       "OFF")			       
    ("old"		       "OLD")			       
    ("on"		       "ON")			       
    ("only"		       "ONLY")			       
    ("open"		       "OPEN")			       
    ("operation"	       "OPERATION")		       
    ("option"	       "OPTION")		       
    ("or"		       "OR")			       
    ("order"	       "ORDER")		       
    ("ordinality"	       "ORDINALITY")		       
    ("out"		       "OUT")			       
    ("outer"	       "OUTER")		       
    ("output"	       "OUTPUT")		       
    ("pad"		       "PAD")			       
    ("parameter"	       "PARAMETER")		       
    ("parameters"	       "PARAMETERS")		       
    ("partial"	       "PARTIAL")		       
    ("path"		       "PATH")			       
    ("postfix"	       "POSTFIX")		       
    ("prefix"	       "PREFIX")		       
    ("preorder"	       "PREORDER")		       
    ("prepare"	       "PREPARE")		       
    ("preserve"	       "PRESERVE")		       
    ("primary"	       "PRIMARY")		       
    ("prior"	       "PRIOR")		       
    ("privileges"	       "PRIVILEGES")		       
    ("procedure"	       "PROCEDURE")		       
    ("public"	       "PUBLIC")		       
    ("read"		       "READ")			       
    ("reads"	       "READS")		       
    ("recursive"	       "RECURSIVE")		       
    ("references"	       "REFERENCES")		       
    ("referencing"	       "REFERENCING")		       
    ("relative"	       "RELATIVE")		       
    ("restrict"	       "RESTRICT")		       
    ("result"	       "RESULT")		       
    ("return"	       "RETURN")		       
    ("returns"	       "RETURNS")		       
    ("revoke"	       "REVOKE")		       
    ("right"	       "RIGHT")		       
    ("role"		       "ROLE")			       
    ("rollback"	       "ROLLBACK")		       
    ("rollup"	       "ROLLUP")		       
    ("routine"	       "ROUTINE")		       
    ("rows"		       "ROWS")			       
    ("savepoint"	       "SAVEPOINT")		       
    ("schema"	       "SCHEMA")		       
    ("scroll"	       "SCROLL")		       
    ("search"	       "SEARCH")		       
    ("second"	       "SECOND")		       
    ("section"	       "SECTION")		       
    ("select"	       "SELECT")		       
    ("sequence"	       "SEQUENCE")		       
    ("session"	       "SESSION")		       
    ("set"		       "SET")			       
    ("sets"		       "SETS")			       
    ("size"		       "SIZE")			       
    ("some"		       "SOME")			       
    ("space"	       "SPACE")		       
    ("specific"	       "SPECIFIC")		       
    ("specifictype"	       "SPECIFICTYPE")		       
    ("sql"		       "SQL")			       
    ("sqlexception"	       "SQLEXCEPTION")		       
    ("sqlstate"	       "SQLSTATE")		       
    ("sqlwarning"	       "SQLWARNING")		       
    ("start"	       "START")		       
    ("state"	       "STATE")		       
    ("statement"	       "STATEMENT")		       
    ("static"	       "STATIC")		       
    ("structure"	       "STRUCTURE")		       
    ("table"	       "TABLE")		       
    ("temporary"	       "TEMPORARY")		       
    ("terminate"	       "TERMINATE")		       
    ("than"		       "THAN")			       
    ("then"		       "THEN")			       
    ("timezone_hour"       "TIMEZONE_HOUR")	       
    ("timezone_minute"     "TIMEZONE_MINUTE")	       
    ("to"		       "TO")			       
    ("trailing"	       "TRAILING")		       
    ("transaction"	       "TRANSACTION")		       
    ("translation"	       "TRANSLATION")		       
    ("trigger"	       "TRIGGER")		       
    ("true"		       "TRUE")			       
    ("under"	       "UNDER")		       
    ("union"	       "UNION")		       
    ("unique"	       "UNIQUE")		       
    ("unknown"	       "UNKNOWN")		       
    ("unnest"	       "UNNEST")		       
    ("update"	       "UPDATE")		       
    ("usage"	       "USAGE")		       
    ("using"	       "USING")		       
    ("value"	       "VALUE")		       
    ("values"	       "VALUES")		       
    ("variable"	       "VARIABLE")		       
    ("view"		       "VIEW")			       
    ("when"		       "WHEN")			       
    ("whenever"	       "WHENEVER")		       
    ("where"	       "WHERE")		       
    ("with"		       "WITH")			       
    ("without"	       "WITHOUT")		       
    ("work"		       "WORK")			       
    ("write"	       "WRITE")		       
    ("year"		       "YEAR")                            
 ("ascii" 				      "ASCII")
 ("avg" 				      "AVG")
 ("bdmpolyfromtext" 			      "BDMPOLYFROMTEXT")
 ("bdmpolyfromwkb" 			      "BDMPOLYFROMWKB")
 ("bdpolyfromtext"			      "BDPOLYFROMTEXT")
 ("bdpolyfromwkb" 			      "BDPOLYFROMWKB")
 ("benchmark" 				      "BENCHMARK")
 ("bin" 				      "BIN")
 ("bit_and" 				      "BIT_AND")
 ("bit_length" 				      "BIT_LENGTH")
 ("bit_or"				      "BIT_OR")
 ("bit_xor" 				      "BIT_XOR")
 ("both" 				      "BOTH")
 ("cast" 				      "CAST")
 ("char_length" 			      "CHAR_LENGTH")
 ("character_length" 			      "CHARACTER_LENGTH")
 ("coalesce"				      "COALESCE")
 ("concat" 				      "CONCAT")
 ("concat_ws" 				      "CONCAT_WS")
 ("connection_id" 			      "CONNECTION_ID")
 ("conv" 				      "CONV")
 ("convert" 				      "CONVERT")
 ("count"				      "COUNT")
 ("curdate" 				      "CURDATE")
 ("current_date" 			      "CURRENT_DATE")
 ("current_time" 			      "CURRENT_TIME")
 ("current_timestamp" 			      "CURRENT_TIMESTAMP")
 ("curtime"				      "CURTIME")
 ("elt" 				      "ELT")
 ("encrypt" 				      "ENCRYPT")
 ("export_set" 				      "EXPORT_SET")
 ("field" 				      "FIELD")
 ("find_in_set" 			      "FIND_IN_SET")
 ("found_rows" 				      "FOUND_ROWS")
 ("from"				      "FROM")
 ("geomcollfromtext" 			      "GEOMCOLLFROMTEXT")
 ("geomcollfromwkb" 			      "GEOMCOLLFROMWKB")
 ("geometrycollectionfromtext"		      "GEOMETRYCOLLECTIONFROMTEXT")
 ("geometrycollectionfromwkb" 		      "GEOMETRYCOLLECTIONFROMWKB")
 ("geometryfromtext" 			      "GEOMETRYFROMTEXT")
 ("geometryfromwkb"			      "GEOMETRYFROMWKB")
 ("geomfromtext" 			      "GEOMFROMTEXT")
 ("geomfromwkb" 			      "GEOMFROMWKB")
 ("get_lock" 				      "GET_LOCK")
 ("group_concat" 			      "GROUP_CONCAT")
 ("hex" 				      "HEX")
 ("ifnull"				      "IFNULL")
 ("instr" 				      "INSTR")
 ("interval" 				      "INTERVAL")
 ("isnull" 				      "ISNULL")
 ("last_insert_id" 			      "LAST_INSERT_ID")
 ("lcase" 				      "LCASE")
 ("leading"				      "LEADING")
 ("length" 				      "LENGTH")
 ("linefromtext" 			      "LINEFROMTEXT")
 ("linefromwkb" 			      "LINEFROMWKB")
 ("linestringfromtext"			      "LINESTRINGFROMTEXT")
 ("linestringfromwkb" 			      "LINESTRINGFROMWKB")
 ("load_file" 				      "LOAD_FILE")
 ("locate" 				      "LOCATE")
 ("lower" 				      "LOWER")
 ("lpad" 				      "LPAD")
 ("ltrim"				      "LTRIM")
 ("make_set" 				      "MAKE_SET")
 ("master_pos_wait" 			      "MASTER_POS_WAIT")
 ("max" 				      "MAX")
 ("mid" 				      "MID")
 ("min" 				      "MIN")
 ("mlinefromtext"			      "MLINEFROMTEXT")
 ("mlinefromwkb" 			      "MLINEFROMWKB")
 ("mpointfromtext" 			      "MPOINTFROMTEXT")
 ("mpointfromwkb" 			      "MPOINTFROMWKB")
 ("mpolyfromtext"			      "MPOLYFROMTEXT")
 ("mpolyfromwkb" 			      "MPOLYFROMWKB")
 ("multilinestringfromtext" 		      "MULTILINESTRINGFROMTEXT")
 ("multilinestringfromwkb"		      "MULTILINESTRINGFROMWKB")
 ("multipointfromtext" 			      "MULTIPOINTFROMTEXT")
 ("multipointfromwkb" 			      "MULTIPOINTFROMWKB")
 ("multipolygonfromtext"		      "MULTIPOLYGONFROMTEXT")
 ("multipolygonfromwkb" 		      "MULTIPOLYGONFROMWKB")
 ("now" 				      "NOW")
 ("nullif" 				      "NULLIF")
 ("oct" 				      "OCT")
 ("octet_length" 			      "OCTET_LENGTH")
 ("ord"					      "ORD")
 ("pointfromtext" 			      "POINTFROMTEXT")
 ("pointfromwkb" 			      "POINTFROMWKB")
 ("polyfromtext" 			      "POLYFROMTEXT")
 ("polyfromwkb"				      "POLYFROMWKB")
 ("polygonfromtext" 			      "POLYGONFROMTEXT")
 ("polygonfromwkb" 			      "POLYGONFROMWKB")
 ("position" 				      "POSITION")
 ("quote" 				      "QUOTE")
 ("rand"				      "RAND")
 ("release_lock" 			      "RELEASE_LOCK")
 ("repeat" 				      "REPEAT")
 ("replace" 				      "REPLACE")
 ("reverse" 				      "REVERSE")
 ("rpad" 				      "RPAD")
 ("rtrim" 				      "RTRIM")
 ("soundex"				      "SOUNDEX")
 ("space" 				      "SPACE")
 ("std" 				      "STD")
 ("stddev" 				      "STDDEV")
 ("substring" 				      "SUBSTRING")
 ("substring_index" 			      "SUBSTRING_INDEX")
 ("sum" 				      "SUM")
 ("sysdate"				      "SYSDATE")
 ("trailing" 				      "TRAILING")
 ("trim" 				      "TRIM")
 ("ucase" 				      "UCASE")
 ("unix_timestamp" 			      "UNIX_TIMESTAMP")
 ("upper" 				      "UPPER")
 ("user" 				      "USER")
 ("variance"				      "VARIANCE")
    ("use" "USE")

))

    
(define-abbrev-table 'text-mode-abbrev-table '(
    ))

(define-abbrev-table 'vc-annotate-mode-abbrev-table '(
    ))

(define-abbrev-table 'vc-dired-mode-abbrev-table '(
    ))
